ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
}

mockstation {
    testCaseDirectory = "testCase"
    testCaseDirectory = ${?TESTCASE_DIR}

    database {
        path = "~/.mockstation/mockstation.db"
        path = ${?DATABASE_PATH}
    }

    settings {
        resFileFormat = 1  # 1: METHOD_SUFFIX, 2: SIMPLE
        defaultDelayMs = 0
    }
}
